[package]
name = "flatgbf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
file = "1.1.2"
flatgeobuf = "3.27.0"
fs = "0.0.5"
geo = "0.26.0"
io = "0.0.2"
